In [2]:
import numpy as np

In [4]:
A = np.random.rand(5,5)
print(A)
B = np.max(A, axis = 0)
print(B)

[[0.71250462 0.83806805 0.19369663 0.94464797 0.07037512]
 [0.32225905 0.02740744 0.11184229 0.21577618 0.37591746]
 [0.28741685 0.33733806 0.78267125 0.14559806 0.11592059]
 [0.14192996 0.31929081 0.97006727 0.57686258 0.19083668]
 [0.65777255 0.63453323 0.30915263 0.33969046 0.37283624]]
[0.71250462 0.83806805 0.97006727 0.94464797 0.37591746]
